[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[context.production.environment]
  # Estas variables son solo ejemplos y deben configurarse en el panel de Netlify
  # No incluyas valores reales aquí
  REACT_APP_FIREBASE_API_KEY = "from_netlify_ui"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "from_netlify_ui"
  REACT_APP_FIREBASE_PROJECT_ID = "from_netlify_ui"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "from_netlify_ui"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "from_netlify_ui"
  REACT_APP_FIREBASE_APP_ID = "from_netlify_ui"
  REACT_APP_PAYPAL_CLIENT_ID = "from_netlify_ui" 